// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-template/ent/comment"
	"go-template/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CommentUpdate is the builder for updating Comment entities.
type CommentUpdate struct {
	config
	hooks    []Hook
	mutation *CommentMutation
}

// Where appends a list predicates to the CommentUpdate builder.
func (cu *CommentUpdate) Where(ps ...predicate.Comment) *CommentUpdate {
	cu.mutation.Where(ps...)
	return cu
}

// SetAuthor sets the "author" field.
func (cu *CommentUpdate) SetAuthor(i int) *CommentUpdate {
	cu.mutation.ResetAuthor()
	cu.mutation.SetAuthor(i)
	return cu
}

// AddAuthor adds i to the "author" field.
func (cu *CommentUpdate) AddAuthor(i int) *CommentUpdate {
	cu.mutation.AddAuthor(i)
	return cu
}

// SetPostid sets the "postid" field.
func (cu *CommentUpdate) SetPostid(i int) *CommentUpdate {
	cu.mutation.ResetPostid()
	cu.mutation.SetPostid(i)
	return cu
}

// AddPostid adds i to the "postid" field.
func (cu *CommentUpdate) AddPostid(i int) *CommentUpdate {
	cu.mutation.AddPostid(i)
	return cu
}

// SetContent sets the "content" field.
func (cu *CommentUpdate) SetContent(s string) *CommentUpdate {
	cu.mutation.SetContent(s)
	return cu
}

// SetLikes sets the "likes" field.
func (cu *CommentUpdate) SetLikes(i int) *CommentUpdate {
	cu.mutation.ResetLikes()
	cu.mutation.SetLikes(i)
	return cu
}

// AddLikes adds i to the "likes" field.
func (cu *CommentUpdate) AddLikes(i int) *CommentUpdate {
	cu.mutation.AddLikes(i)
	return cu
}

// Mutation returns the CommentMutation object of the builder.
func (cu *CommentUpdate) Mutation() *CommentMutation {
	return cu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (cu *CommentUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, cu.sqlSave, cu.mutation, cu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cu *CommentUpdate) SaveX(ctx context.Context) int {
	affected, err := cu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (cu *CommentUpdate) Exec(ctx context.Context) error {
	_, err := cu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cu *CommentUpdate) ExecX(ctx context.Context) {
	if err := cu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (cu *CommentUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(comment.Table, comment.Columns, sqlgraph.NewFieldSpec(comment.FieldID, field.TypeInt))
	if ps := cu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cu.mutation.Author(); ok {
		_spec.SetField(comment.FieldAuthor, field.TypeInt, value)
	}
	if value, ok := cu.mutation.AddedAuthor(); ok {
		_spec.AddField(comment.FieldAuthor, field.TypeInt, value)
	}
	if value, ok := cu.mutation.Postid(); ok {
		_spec.SetField(comment.FieldPostid, field.TypeInt, value)
	}
	if value, ok := cu.mutation.AddedPostid(); ok {
		_spec.AddField(comment.FieldPostid, field.TypeInt, value)
	}
	if value, ok := cu.mutation.Content(); ok {
		_spec.SetField(comment.FieldContent, field.TypeString, value)
	}
	if value, ok := cu.mutation.Likes(); ok {
		_spec.SetField(comment.FieldLikes, field.TypeInt, value)
	}
	if value, ok := cu.mutation.AddedLikes(); ok {
		_spec.AddField(comment.FieldLikes, field.TypeInt, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, cu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{comment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	cu.mutation.done = true
	return n, nil
}

// CommentUpdateOne is the builder for updating a single Comment entity.
type CommentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CommentMutation
}

// SetAuthor sets the "author" field.
func (cuo *CommentUpdateOne) SetAuthor(i int) *CommentUpdateOne {
	cuo.mutation.ResetAuthor()
	cuo.mutation.SetAuthor(i)
	return cuo
}

// AddAuthor adds i to the "author" field.
func (cuo *CommentUpdateOne) AddAuthor(i int) *CommentUpdateOne {
	cuo.mutation.AddAuthor(i)
	return cuo
}

// SetPostid sets the "postid" field.
func (cuo *CommentUpdateOne) SetPostid(i int) *CommentUpdateOne {
	cuo.mutation.ResetPostid()
	cuo.mutation.SetPostid(i)
	return cuo
}

// AddPostid adds i to the "postid" field.
func (cuo *CommentUpdateOne) AddPostid(i int) *CommentUpdateOne {
	cuo.mutation.AddPostid(i)
	return cuo
}

// SetContent sets the "content" field.
func (cuo *CommentUpdateOne) SetContent(s string) *CommentUpdateOne {
	cuo.mutation.SetContent(s)
	return cuo
}

// SetLikes sets the "likes" field.
func (cuo *CommentUpdateOne) SetLikes(i int) *CommentUpdateOne {
	cuo.mutation.ResetLikes()
	cuo.mutation.SetLikes(i)
	return cuo
}

// AddLikes adds i to the "likes" field.
func (cuo *CommentUpdateOne) AddLikes(i int) *CommentUpdateOne {
	cuo.mutation.AddLikes(i)
	return cuo
}

// Mutation returns the CommentMutation object of the builder.
func (cuo *CommentUpdateOne) Mutation() *CommentMutation {
	return cuo.mutation
}

// Where appends a list predicates to the CommentUpdate builder.
func (cuo *CommentUpdateOne) Where(ps ...predicate.Comment) *CommentUpdateOne {
	cuo.mutation.Where(ps...)
	return cuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (cuo *CommentUpdateOne) Select(field string, fields ...string) *CommentUpdateOne {
	cuo.fields = append([]string{field}, fields...)
	return cuo
}

// Save executes the query and returns the updated Comment entity.
func (cuo *CommentUpdateOne) Save(ctx context.Context) (*Comment, error) {
	return withHooks(ctx, cuo.sqlSave, cuo.mutation, cuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cuo *CommentUpdateOne) SaveX(ctx context.Context) *Comment {
	node, err := cuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (cuo *CommentUpdateOne) Exec(ctx context.Context) error {
	_, err := cuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cuo *CommentUpdateOne) ExecX(ctx context.Context) {
	if err := cuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (cuo *CommentUpdateOne) sqlSave(ctx context.Context) (_node *Comment, err error) {
	_spec := sqlgraph.NewUpdateSpec(comment.Table, comment.Columns, sqlgraph.NewFieldSpec(comment.FieldID, field.TypeInt))
	id, ok := cuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Comment.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := cuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, comment.FieldID)
		for _, f := range fields {
			if !comment.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != comment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := cuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cuo.mutation.Author(); ok {
		_spec.SetField(comment.FieldAuthor, field.TypeInt, value)
	}
	if value, ok := cuo.mutation.AddedAuthor(); ok {
		_spec.AddField(comment.FieldAuthor, field.TypeInt, value)
	}
	if value, ok := cuo.mutation.Postid(); ok {
		_spec.SetField(comment.FieldPostid, field.TypeInt, value)
	}
	if value, ok := cuo.mutation.AddedPostid(); ok {
		_spec.AddField(comment.FieldPostid, field.TypeInt, value)
	}
	if value, ok := cuo.mutation.Content(); ok {
		_spec.SetField(comment.FieldContent, field.TypeString, value)
	}
	if value, ok := cuo.mutation.Likes(); ok {
		_spec.SetField(comment.FieldLikes, field.TypeInt, value)
	}
	if value, ok := cuo.mutation.AddedLikes(); ok {
		_spec.AddField(comment.FieldLikes, field.TypeInt, value)
	}
	_node = &Comment{config: cuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, cuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{comment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	cuo.mutation.done = true
	return _node, nil
}
