// Code generated by ent, DO NOT EDIT.

package ent

import (
	"go-template/ent/post"
	"go-template/ent/schema"
	"go-template/ent/user"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	postFields := schema.Post{}.Fields()
	_ = postFields
	// postDescLikes is the schema descriptor for likes field.
	postDescLikes := postFields[3].Descriptor()
	// post.DefaultLikes holds the default value on creation for the likes field.
	post.DefaultLikes = postDescLikes.Default.(int)
	// postDescCreateAt is the schema descriptor for create_at field.
	postDescCreateAt := postFields[4].Descriptor()
	// post.DefaultCreateAt holds the default value on creation for the create_at field.
	post.DefaultCreateAt = postDescCreateAt.Default.(func() time.Time)
	// postDescUpdateAt is the schema descriptor for update_at field.
	postDescUpdateAt := postFields[5].Descriptor()
	// post.UpdateDefaultUpdateAt holds the default value on update for the update_at field.
	post.UpdateDefaultUpdateAt = postDescUpdateAt.UpdateDefault.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreateAt is the schema descriptor for create_at field.
	userDescCreateAt := userFields[10].Descriptor()
	// user.DefaultCreateAt holds the default value on creation for the create_at field.
	user.DefaultCreateAt = userDescCreateAt.Default.(func() time.Time)
	// userDescUpdateAt is the schema descriptor for update_at field.
	userDescUpdateAt := userFields[11].Descriptor()
	// user.UpdateDefaultUpdateAt holds the default value on update for the update_at field.
	user.UpdateDefaultUpdateAt = userDescUpdateAt.UpdateDefault.(func() time.Time)
}
